### ISSUE TITLE
open AixLib with OpenModelica, "Grammatik Fehler" and "Skripting Fehler"

### ISSUE THREAD

**Issue by R33B** [RWTH-EBC/AixLib#250] opened 2016-05-23 13:16 UTC
On trying to open the AixLib with OpenModelica, i get the following errors (WIN10, OpenModelica 1.9.6), the import with Dymola works, but can't be used due to test-version:

[1] Grammatik Warnung
The package.order file does not list all .mo files and directories (containing package.mo) present in its directory.
Missing names are:
        partialReducedOrderModel

[2] Grammatik Fehler
Expected the package to have name partialReducedOrderModel, but got PartialReducedOrderModel.

[3] Skripting Fehler
Failed to load package AixLib () using MODELICAPATH 
..\AixLib-master\;C:/OpenModelica1.9.6/lib/omlibrary.

**Comment by marcusfuchs** [comment] 2016-05-23 14:34
Thanks for pointing our attention to these issues, we will fix [1] and [2], while [3] does not seem to be caused by bugs in the library.

**Comment by R33B** [comment] 2016-05-23 18:51
You are welcome.
Please, let me know when [1] and [2] are fixed, so that i can check whether [3] is an aftereffect.

**Comment by marcusfuchs** [comment] 2016-05-24 10:57
@R33B 
These problems should be fixed now. Can you confirm this?

**Comment by R33B** [comment] 2016-05-24 11:23
I can confirm this, but there are still problems as seen below:

[1] 13:18:57 Skripting Fehler
Failed to load package AixLib (default) using MODELICAPATH C:/OpenModelica1.9.6/lib/omlibrary.

[2] 13:19:28 Grammatik Fehler
[C:/Users/Robin Beer/Downloads/AixLib-issue250_OMBugs/AixLib/UsersGuide/package.mo: 2:1-12:15]: UsersGuide was referenced in the package.order file, but was not found in package.mo, UsersGuide/package.mo or UsersGuide.mo.

[3] 13:19:28 Skripting Fehler
Failed to load package AixLib () using MODELICAPATH C:\Users\Robin Beer\Downloads\AixLib-issue250_OMBugs\;C:/OpenModelica1.9.6/lib/omlibrary.

[4] 13:21:34 Grammatik Fehler
[C:/Users/Robin Beer/Downloads/AixLib-issue250_OMBugs/AixLib/UsersGuide/package.mo: 2:1-12:15]: UsersGuide was referenced in the package.order file, but was not found in package.mo, UsersGuide/package.mo or UsersGuide.mo.

[5] 13:21:34 Skripting Fehler
Failed to load package AixLib () using MODELICAPATH C:\Users\Robin Beer\Downloads\AixLib-issue250_OMBugs\;C:/OpenModelica1.9.6/lib/omlibrary.

**Comment by marcusfuchs** [comment] 2016-05-24 12:47
@R33B 
Interesting that I did not get this error on the 1.10.0 nightly build, but I hope that also your new problem has been fixed now.

**Comment by R33B** [comment] 2016-05-24 14:40
Apparently the nightly builds really fix some bugs. Nice to know.

With OM1.9.6 I can open the library and most of the classes and examples, except of some complex ones, where omedit collapses.

Therewith this issue can be closed, thank you for the support.

**Comment by marcusfuchs** [comment] 2016-05-24 15:48
Yes, unfortunately we can not yet support full coverage of the library by OpenModelica, but we want to at least always be able to open the library in OM without errors, so thanks again for pointing our attention to the bugs that now are hopefully all fixed.

**Closed by marcusfuchs** 2016-05-24 15:48 UTC
