### ISSUE TITLE
Move AixLib.Fluid.Storage.Storage in Obsolete package and rename AixLib.Fluid.Storage.BufferStorage

### ISSUE THREAD

**Issue by LauraMaier** [RWTH-EBC/AixLib#1171] opened 2021-10-21 11:44 UTC
The model `AixLib.Fluid.Storage.Storage` is a simplified buffer storage model, which is used only rarely.
Additionally, a second buffer storage model exists in `AixLib.Fluid.Storage.BufferStorage`, which is more detailed and validated.
This is why, I propose to move the simplified model in the Obsolete package.
Plus, the model `AixLib.Fluid.Storage.BufferStorage` can also be used as e.g. a domestic hot water storage, which is why we propose refactoring it to  `AixLib.Fluid.Storage.ThermalEnergyStorage`.

**Comment by LauraMaier** [comment] 2022-01-04 09:26
Update: 
AixLib.Fluid.Storage.Storage will not be deleted because the simple storage might still be needed for broad parameter studies (i.e. varying the storage volume). 

Therefore, the issue comprises the following tasks:

- [ ] Rename AixLib.Fluid.Storage.BufferStorage to AixLib.Fluid.Storage.DetailedStorage
- [ ] Rename AixLib.Fluid.Storage.Storage to AixLib.Fluid.Storage.SimpleStorage
- [ ] Update Documentation to clarify differences between storage models and purposes
- [ ] Spring cleaning in AixLib.Fluid.Storage.Storage

**Comment by FWuellhorst** [comment] 2022-01-04 09:31
Alternative:
Check which integers depend on the volume and make them not final anymore.
```
final parameter Integer nHC1Up=integer(ceil(data.hHC1Up/(data.hTank/n)));
 final parameter Integer nHC1Low=integer(floor(data.hHC1Low/(data.hTank/n))+1);
 final parameter Integer disHC1 = nHC1Up-nHC1Low+1;

 final parameter Integer nHC2Up=integer(ceil(data.hHC2Up/(data.hTank/n)));
 final parameter Integer nHC2Low=integer(floor(data.hHC2Low/(data.hTank/n))+1);
 final parameter Integer disHC2 = nHC2Up-nHC2Low+1;

 final parameter Integer nHR=integer(AixLib.Utilities.Math.Functions.round(data.hHR/(data.hTank/n) + 0.5,0));

 final parameter Integer nTS1=integer(AixLib.Utilities.Math.Functions.round(data.hTS1/(data.hTank/n) + 0.5,0));
 final parameter Integer nTS2=integer(AixLib.Utilities.Math.Functions.round(data.hTS2/(data.hTank/n) + 0.5,0));

 final parameter Integer nLowerPortDemand=integer(max(AixLib.Utilities.Math.Functions.round(data.hLowerPortDemand/(data.hTank/n) + 0.5,0),1));
 final parameter Integer nUpperPortDemand=integer(min(AixLib.Utilities.Math.Functions.round(data.hUpperPortDemand/(data.hTank/n) + 0.5,0),n));
 final parameter Boolean inpLowLayDemand=(nLowerPortDemand == 1); //if there is an input at the lowest layer
 final parameter Boolean inpHigLayDemand=(nUpperPortDemand == n);

 final parameter Integer nLowerPortSupply=integer(max(AixLib.Utilities.Math.Functions.round(data.hLowerPortSupply/(data.hTank/n) + 0.5,0),1));
 final parameter Integer nUpperPortSupply=integer(min(AixLib.Utilities.Math.Functions.round(data.hUpperPortSupply/(data.hTank/n) + 0.5,0),n));
 final parameter Boolean inpLowLaySupply=(nLowerPortSupply == 1); //if there is an input at the lowest layer
 final parameter Boolean inpHigLaySupply=(nUpperPortSupply == n);

 final parameter Integer[n] inpActLay = cat(1,{if (nLowerPortDemand==k or nLowerPortSupply==k) then (if (nUpperPortDemand==k or nUpperPortSupply==k) then 2 else 1) else (if (nUpperPortDemand==k or nUpperPortSupply==k) then 1 else 0) for k in 1:n});
 final parameter Integer[n] portsLayer=cat(1,{if inpActLay[1]==1 then 3 else 1},{inpActLay[k]*2+2 for k in 2:n-1},{if inpActLay[n]==1 then 3 else 1});

```

**Comment by LauraMaier** [comment] 2022-07-14 13:44
I did not put the simple storage in the Obsolete package as it is still needed for parameter studies, etc.

**Comment by FWuellhorst** [comment] 2022-08-02 06:28
@DaJansenGit : Did the bot just close the issue and the branch?

**Comment by DaJansenGit** [comment] 2022-08-02 07:18
The issue was closed, but the branch not. The problem is that the CI associated this issue with [this branch](https://github.com/RWTH-EBC/AixLib/tree/Issue1171_Move_AixLib_Fluid_Storage_Storage_in_Obsolete_package_and_rename_AixLib_Fluid_Storage_BufferStorage) which was created by the already deactivated GitHub action which we found not convenient. But the pushes made by @LauraMaier are against [this branch ](https://github.com/RWTH-EBC/AixLib/tree/issue1171_StorageSpringCleaning). 

If you are fine with it, I would just delete the automatic created branch, reopen this issue and go on with the work in [this branch ](https://github.com/RWTH-EBC/AixLib/tree/issue1171_StorageSpringCleaning). :)

**Comment by FelixStege** [comment] 2023-02-13 13:10
@LauraMaier will this be tackled on the upcoming hackday or can we remove the label?

**Closed** 2024-07-18 12:14 UTC
