### ISSUE TITLE
Rebuilding the reversible HP model based on a new general partial model for reversible HPs and chillers

### ISSUE THREAD

**Issue by JulianMatthes** [RWTH-EBC/AixLib#715] opened 2019-05-08 09:50 UTC
**What is the problem?**

A new reversible chiller model based on the structure of the reversible heat pump model is required. To optimize its usability a new partial model for thermal machines (e.g. heat pumps, chillers) shall be developed. Furthermore the previous reversible heat pump model and the new reversible chiller model are to be extended from this partial model. Also, the improvements in applicability include variable naming.
For that reason the variable naming when changing the operation mode shall fit to its belonging function (evaporator or condenser).

**How do we want to solve it?**

A new partial model shall be developed. The heat pump and the chiller model extend from this partial model placed in the base class of the Fluid library. A query is defined as to whether reversible operation is possible. In addition, the elements on the condenser and evaporator side are named and connected starting from the main operating mode (heating or cooling).
Finally belonging FastHVAC models are to be adapted analogously.

**Comment by DaJansenGit** [comment] 2019-09-25 12:22
@JulianMatthes please have a look at #696 and check if everything still works or if their are necessary changes. If no changes needed, can we merge this into development?

**Comment by JulianMatthes** [comment] 2019-09-26 14:17
@DaJansenGit #769 is based on the current dev and this branch was already 2 months behind it. So changes had to be made merging it into this branch. They can be found in the belonging PR #724

**Comment by KremerMartin** [comment] 2019-10-08 06:54
@DaJansenGit Can you have a look at the failed check in PR #724 ? As I see it, the branch will be ready to merge after merging the last changes in the development into this branch, if the tests pass. Maybe you have got a clue, what went wrong. I am no expert on CI...

**Comment by DaJansenGit** [comment] 2019-10-08 07:14
@KremerMartin this seems to be due to missing regression test results. We have the same problem with #774. In the next days I will try to update the regression test files.

**Comment by DaJansenGit** [comment] 2019-12-16 11:28
closed by merge of #724

**Closed by DaJansenGit** 2019-12-16 11:28 UTC
