### ISSUE TITLE
Evaluate weather model

### ISSUE THREAD

**Issue by marcusfuchs** [RWTH-EBC/AixLib#181] opened 2016-04-04 15:53 UTC
With the planned changes in the LOM in A60, it may be better to convert to the A60 weather reader and weather bus.

**Comment by AnaConstantin** [comment] 2017-02-14 10:35
Compare  AixLib.BoundaryConditions.WeatherData.ReaderTMY3 with AixLib.Building.Components.Weather.Weather and decide which model/combination to use.
Points to clear up before decision:

- [ ] Compare TMY3 with TRY format and for missing data types check processing algroithms according to http://climate.onebuilding.org/ - make a list

- [ ] Compare simulation speed with solar radiation model in weather model agiants wall model

- [ ] Analyse how the introduction of a bus connector might affect existing AixLib models - make a list

**Comment by mlauster** [comment] 2017-02-22 10:41
Here you get the tremendous Elements software: http://bigladdersoftware.com/projects/elements/

**Comment by AnaConstantin** [comment] 2017-02-22 11:06
Additionally for Comparison TMY3 to TRY see if the algorithms used for transforming TMY to TRY for solar radiation can be to some extent re-utilised

**Comment by PMehrfeld** [comment] 2017-03-01 11:23
As a hint: Since there is still some manual work necessary working with elements, [this part of the User Guide](http://bigladdersoftware.com/projects/elements/docs/user-guide/tutorial-create-from-scratch.html) might be helpful. (Thanks @mlauster)

**Comment by AnaConstantin** [comment] 2017-06-22 11:13
I just finished some work on comparing if the calculation of the solar radiation is better left in the weather model, or moved in the wall model.
First I transforemed all the angle calculations from the sun model and the solar radiation models to radian, instead of degrees. This saves minimal time, but I like it better.
Then I adapted both the Liu and the Perez model to work with a bus system.
I moved the solar calculation model inside the wall model and did calculations with five and seven walls. When using the model inside the wall, the CPU rises, a lot more for Perez than for Liu. All the models are available in branch issue181_weatherModel, is someone wants to check.
So my suggestion is to keep the calculation in the weather model, but maybe transmit the information by bus to the wall model, and have each wall choose the corect radiation based on orientation. I will open an issue for this.
Additionally I would open an issue for the  conversion to radian from degree for the angle calculations.

**Comment by AnaConstantin** [comment] 2017-06-22 11:14
As far as transmitting weather information by bus down to the wall model, I think it is a great idea, since outer walls are the ones needing the modes information and can divide it inside the model anyway for each component. It will be dealt in in the issue on bus connectors and walls.

**Comment by PMehrfeld** [comment] 2017-07-24 14:01
There are two branches:

- issue181_weatherCompare
- issue181_weatherModel

@mlauster you have committed to weatherCompare whilst @AnaConstantin has worked in weatherModel.

Is this correct or should it be merged to one branch?

**Comment by AnaConstantin** [comment] 2017-07-24 14:05
there are two different aspects for the same issue. It can be mearged in one branch if it is a problem. The issue181_weatherModel is to be used more as a reference, as nothing done there will be merged in AixLib. I tested several type of models with solar radiation inside or outside the mdoelt o decide which is quicker. I will have to archive the models in a way so the results can be easily reproduced.

**Comment by mlauster** [comment] 2017-07-24 14:09
Same for me, I just compared TRY and TMY data sets, but it does not need to go into development or master, we can delete the branch

**Comment by PMehrfeld** [comment] 2017-07-24 14:15
Thanks for your feedback. I deleted branch `weahterCompare`.
@AnaConstantin: When you have thought of a way to archive the branch's interesting models, please delete this branch :)
And of course close this issue, if there are no further open points.

**Comment by mlauster** [comment] 2017-10-12 18:40
If I remember correctly, @AnaConstantin and me decided to move to the new weather model from IBPSA library. However, to allow a smooth transition for the users, we will keep the old model for a while and possibly move it as part of #276 . Thus, I will close this issue.

**Closed by mlauster** 2017-10-12 18:40 UTC
Labels: Annex 60 integration
